### PR TITLE
chore(deps): WX base sdk version 2.9.0  suport a new Cnavas 2D API

### PR DESCRIPTION
**Pull request by JunaYa**
[wx new doc](https://developers.weixin.qq.com/miniprogram/en/dev/component/canvas.html)

now IDE advices

[/__pageframe__/pages/home/index] canvas 2d 接口支持同层渲染且性能更佳，建议切换使用。详见文档：https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html#Canvas-2D-%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81

### CODE REVIEW

**Comment by chanind** [comment]
Good find! I'll test this out and get it merged assuming it seems to work still

**Comment by zhifengjiang** [comment]
Please merge this, I have tested it.

**Comment by chanind** [comment]
Apologies for the delay! Looks good!

**Pull request merged**
